use_frameworks!
inhibit_all_warnings!

target 'ERNiftyExtensions_Example' do
  pod 'ERNiftyExtensions', :path => '../'

  target 'ERNiftyExtensions_Tests' do
    inherit! :search_paths

    
  end
end
