use_frameworks!
inhibit_all_warnings!
platform :ios, '10.0'

target 'ERNiftyExtensions_Example' do
  pod 'ERNiftyExtensions', :path => '../'

  target 'ERNiftyExtensions_Tests' do
    inherit! :search_paths

    
  end
end
